### PR TITLE
license info, switch to pypi, add {{ name }}

### PR DESCRIPTION
**Pull request by pmlandwehr**
Fixes https://github.com/conda-forge/olefile-feedstock/issues/1

This pull is intended to force a rebuild to address [issue 1](https://github.com/conda-forge/olefile-feedstock/issues/1). I've also added a `{{ name }}` variable and switched to downloading from [pypi](https://pypi.python.org/pypi/olefile/0.42.1) via [pypi.io](https://pypi.org/project/olefile/0.42.1/).  It's worth noting that `olefile` is now at `0.43`, so the version could also be ticked.

### CODE REVIEW

**Comment by pmlandwehr** [comment]
@jakirkham do you have any idea what's up with the Circle CI error? It's most peculiar.

**Comment by jakirkham** [comment]
Seems like a minor hiccup on CircleCI when trying to pull the Docker container. This isn't a frequent error, but have seen it before. Went ahead and restarted it. Expect it should pass.

**Comment by jakirkham** [comment]
Added the fixes note in the OP. Thanks for putting this together, @pmlandwehr. 😄

**Comment by pmlandwehr** [comment]
Any chance of a merge here, @ericdill?

**Pull request merged**
